nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    image: nodeapp:0.0.2
    links:
        - redis
    ports:
        - "3000"
node2:
    image: nodeapp:0.0.2
    links:
        - redis
    ports:
        - "3000"
node3:
    image: nodeapp:0.0.2
    links:
        - redis
    ports:
        - "3000"
redis:
    image: redis
    ports:
        - "6379"